apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.app.name }}
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
status:
  loadBalancer: {}
